[package]
name = "ulam-spiral"
version = "0.1.0"
authors = ["sireliah <sajuukk@gmail.com>"]
edition = "2021"

[dependencies]
image = "*"
glib = "*"
gio = "*"
gdk = "*"
gtk = "*"
gdk-pixbuf = "*"
rand = "*"
